// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-336UPtisw0jjx6trTd0A-N7Hm35qD4Y',
    appId: '1:69394371572:web:cb04b5a6a6a64dab779fa1',
    messagingSenderId: '69394371572',
    projectId: 'api-key-manager-81047',
    authDomain: 'api-key-manager-81047.firebaseapp.com',
    storageBucket: 'api-key-manager-81047.appspot.com',
    measurementId: 'G-53E5365DM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgmPDO-r2Q_GQ_cWLxQ60aBOVeQA5mCFs',
    appId: '1:69394371572:android:04466efbeeae9329779fa1',
    messagingSenderId: '69394371572',
    projectId: 'api-key-manager-81047',
    storageBucket: 'api-key-manager-81047.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxoTQSK5ky9v2k1jsP-NCrPeOK4trRTgo',
    appId: '1:69394371572:ios:b509dcb340849a1d779fa1',
    messagingSenderId: '69394371572',
    projectId: 'api-key-manager-81047',
    storageBucket: 'api-key-manager-81047.appspot.com',
    iosBundleId: 'com.example.apikeyManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxoTQSK5ky9v2k1jsP-NCrPeOK4trRTgo',
    appId: '1:69394371572:ios:fffd699087266904779fa1',
    messagingSenderId: '69394371572',
    projectId: 'api-key-manager-81047',
    storageBucket: 'api-key-manager-81047.appspot.com',
    iosBundleId: 'com.example.apikeyManager.RunnerTests',
  );
}
